// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:44244070222:web:bf4a23fc01c27dc8e2781f',
    messagingSenderId: '44244070222',
    projectId: 'karigarpk',
    authDomain: 'karigarpk.firebaseapp.com',
    storageBucket: 'karigarpk.firebasestorage.app',
    measurementId: 'G-CC42FT9W3Z',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '',
    appId: '1:44244070222:android:a301030c85628a1ce2781f',
    messagingSenderId: '44244070222',
    projectId: 'karigarpk',
    storageBucket: 'karigarpk.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:44244070222:ios:729ac998ac9f3d72e2781f',
    messagingSenderId: '44244070222',
    projectId: 'karigarpk',
    storageBucket: 'karigarpk.firebasestorage.app',
    iosBundleId: 'com.example.karigar',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS'] ?? '',
    appId: '1:44244070222:ios:729ac998ac9f3d72e2781f',
    messagingSenderId: '44244070222',
    projectId: 'karigarpk',
    storageBucket: 'karigarpk.firebasestorage.app',
    iosBundleId: 'com.example.karigar',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB'] ?? '',
    appId: '1:44244070222:web:b5d27b5114b9f006e2781f',
    messagingSenderId: '44244070222',
    projectId: 'karigarpk',
    authDomain: 'karigarpk.firebaseapp.com',
    storageBucket: 'karigarpk.firebasestorage.app',
    measurementId: 'G-R07RVX711B',
  );
}
